issuer: https://token.actions.githubusercontent.com
subject: "repo:Depthmark/repositories-settings:ref:refs/heads/main"

claim_pattern:
  workflow_ref: "Depthmark/repositories-settings/.github/workflows/release-please.yml@refs/heads/main"

permissions:
  contents: write
  pull_requests: write
